export const LOGIN_REDUCER = {
  SET_FIELD: "SET_FIELD",
  SET_USERNAME: "SET_USERNAME",
  SET_PASSWORD: "SET_PASSWORD",
  SET_USERNAME_ERROR: "SET_USERNAME_ERROR",
  SET_PASSWORD_ERROR: "SET_PASSWORD_ERROR",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  RESET_ERRORS: "RESET_ERRORS",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILED: "LOGIN_FAILED",
};

export const PROJECT_REDUCER = {
  SET_PROJECTS: "SET_PROJECTS",
  GET_PROJECTS: "GET_PROJECTS",
};